const apparelAndAccessoriesItems = [
    "Bags",
    "Clothing Accessories",
    "High-end Jewelry",
    "Men's Clothing",
    "Men's Shoes",
    "Ordinary Jewelry",
    "Other Apparel & Accessories",
    "Traditional & Ceremonial Clothing",
    "Watches",
    "Wearable Tech Devices",
    "Women's Clothing",
    "Women's Shoes",
];
const appliances = [
    "Digital Devices",
    "Home Appliances",
    "Kitchen & Bathroom Appliances",
    "Large Appliances",
    "Other Appliances",
    "Personal Care Appliances",
]
const apps = [
    "Audio & Video Players",
    "Business & Productivity",
    "Education",
    "Financial Services",
    "Health & Fitness",
    "Life & Leisure",
    "News & Reading",
    "Online Shopping",
    "Other Apps",
    "Parenting",
    "Photography",
    "Social",
    "Travel",
    "Utilities",
]
const babyKidsMeternity = [
    "Baby Bedding",
    "Baby Feeding Supplies",
    "Baby Food",
    "Baby Formula",
    "Baby Hygiene Products",
    "Baby Shoes",
    "Child Car Seats",
    "Children's Apparel",
    "Diapers & Baby Wipes",
    "Other Baby, Kids & Maternity",
    "Strollers & Cribs",
    "Toys for Kids",
]
const beautyAndPersonalCare = [
    "Aesthetic Medicine",
    "Cosmetics",
    "Feminine Care",
    "Fragrances & Perfumes",
    "Haircare",
    "Oral Care",
    "Other Beauty & Personal Care",
    "Skincare",
    "Wig & Hair Styling"
]
const businessServices = [
    "Agriculture, Forestry, Animal Husbandry & Fishing",
    "Auction Services",
    "Chemical Materials",
    "Constructional Engineering",
    "Electronics & Electrical",
    "Energy Conservation & Environmental Protection",
    "Exhibition Services",
    "Franchising",
    "Machinery & Equipment",
    "Marketing & Advertising",
    "Office Equipment & Supplies",
    "Other Business Services",
    "Professional Consultation",
    "Real Estate & Home Rentals",
    "Recruitment & Job Searching",
    "Safety & Security",
    "Service Outsourcing",
]
const ECommerce = [
    "Big Box Retailers",
    "Large E-commerce Platforms",
    "Small & Medium-sized E-commerce Platforms"
]
const Education = [
    "Early Childhood & Preschool Education",
    "Higher Education",
    "Language Training",
    "Non-academic Training (Hobbies)",
    "Other Education",
    "Overseas Education",
    "Primary & Secondary Education & K-12",
    "Vocational Training",
]
const financialServices = [
    "Commercial Banks",
    "Credit Bureaus",
    "Credit Cards",
    "Crowd Funding",
    "Cryptocurrencies",
    "Foreign Exchange Transactions",
    "Funds",
    "Guarantees",
    "Investment Advisory",
    "Loan Services",
    "Microfinance Companies",
    "Other Financial Services",
    "Pawn Shops",
    "Precious Metals",
    "Securities",
    "Third-Party Payments",
    "Trusts",
]
const foodAndBeverage = [
    "Alcoholic Beverages",
    "Cooking & Recipes",
    "Cuisine",
    "Food & Fresh Produce",
    "Non-alcoholic Beverages",
    "Other Food & Beverage",
]
const Games = [
    "Action",
    "Casino",
    "Hyper-Casual",
    "Kids",
    "Match",
    "Other",
    "Party",
    "Puzzle",
    "Racing",
    "RPG",
    "Shooting",
    "Simulation",
    "Sports",
    "Strategy",
    "Tabletop",
]
const Health = [
    "Dietary Supplements",
    "Medical Information",
    "Medical Services",
    "Medicine",
    "Other Health",
]
const homeImprovement = [
    "Construction Materials & Lighting",
    "Furniture",
    "Hardware & Electrical",
    "Home Decor",
    "Interior Design & Decorating Services",
    "Other Home Improvement",
    "Power Strips & Socket",
]
const houseHoldProducts = [
    "Cleaning Appliances",
    "Cleaning Supplies",
    "Coffee Accessories",
    "Daily Essentials",
    "Glasses & Drinkware",
    "Kitchen Accessories",
    "Laundry",
    "Leather Care",
    "Other Household Products",
    "Pest Control",
    "Storage Products",
    "Tea Sets",
    "Tissues & Wet Wipes",
    "Toys",
]
const lifeServices = [
    "Beauty & Personal Care",
    "Consumer Services",
    "Dating & Matchmaking Services",
    "Exercise & Fitness",
    "Gardening",
    "Gifts & Flowers",
    "Housekeeping",
    "Internet Services",
    "Other Life Services",
    "Photography",
    "Shopping Services",
    "Used Good Sales Platforms",
    "Utilities Payments",
    "Wedding Celebrations",
    "Wedding Photography",
]
const newsAndEntertainment = [
    "Anime",
    "Astrology",
    "Beauty & Personal Care",
    "Business & Economy",
    "Car Information",
    "Celebrities & Gossip",
    "Charity & Public Welfare",
    "Collectables & Antiques",
    "Culture & Art",
    "Culture & History",
    "E-commerce Information",
    "Environmental Protection",
    "Food & Cooking",
    "Games & Utility Software",
    "General Information",
    "Humor",
    "Law",
    "Lifestyle News",
    "Live Events",
    "Military",
    "Movies",
    "Other News & Entertainment",
    "Pet Information",
    "Politics",
    "Reading",
    "Real Estate Information",
    "Relationship Information",
    "Science & Technology",
    "Social Media Account Promotion",
    "Sports & Fitness",
    "Streaming Site",
    "Tourist Information",
    "TV Drama & Series",
    "TV Variety Shows",
]
const pets = [
    "Other Pets",
    "Pet Grooming",
    "Pet Healthcare",
    "Pet Household Products",
    "Pet Toys",
    "Pet Travel Accessories",
    "Pet Treats",
    "Petfood",
]
const sportsAndOutdoor = [
    "Outdoor Equipment",
    "Sports & Equipment",
]
const techElectronics = [
    "Cell Phones",
    "Computer Accessories",
    "Computer Repair",
    "Computers",
    "Computers Components",
    "Gaming Devices",
    "Network Products",
    "Office Equipment",
    "Other Tech & Electronics"
]
const travel = [
    "Hotels & Accommodation",
    "Other Travel",
    "Tours & Attractions",
    "Travel Agencies & Services",
]
const vehicleTransportation = [
    "Accessories for 2/3-Wheeled Vehicles",
    "Airplanes",
    "Auto Accessories",
    "Auto Parts",
    "Auto Services",
    "Automobiles",
    "Bicycles",
    "Car Dealerships",
    "Car Rentals",
    "Electric Scooters",
    "Motorcycles",
    "Other Vehicle & Transportation",
    "Used Cars",
    "Water Vehicles",
]
const categories = [
    {
        label: "Apparel & Accessories",
        subcategories: [],
    },
    {
        label: "Appliances",
        subcategories: [],
    },
    {
        label: "Apps",
        subcategories: [],
    },
    {
        label: "Baby, Kids & Maternity",
        subcategories: [],
    },
    {
        label: "Beauty & Personal Care",
        subcategories: [],
    },
    {
        label: "Business Services",
        subcategories: [],
    },
    {
        label: "E-Commerce (Non-app)",
        subcategories: [],
    },
    {
        label: "Education",
        subcategories: [],
    },
    {
        label: "Financial Services",
        subcategories: [],
    },
    {
        label: "Food & Beverage",
        subcategories: [],
    },
    {
        label: "Games",
        subcategories: [],
    },
    {
        label: "Health",
        subcategories: [],
    },
    {
        label: "Home Improvement",
        subcategories: [],
    },
    {
        label: "Household Products",
        subcategories: [],
    },
    {
        label: "Life Services",
        subcategories: [],
    },
    {
        label: "News & Entertainment",
        subcategories: [],
    },
    {
        label: "Pets",
        subcategories: [],
    },
    {
        label: "Sports & Outdoor",
        subcategories: [],
    },
    {
        label: "Tech & Electronics",
        subcategories: [],
    },
    {
        label: "Travel",
        subcategories: [],
    },
    {
        label: "Vehicle & Transportation",
        subcategories: [],
    },
];

export { apparelAndAccessoriesItems, appliances, apps, babyKidsMeternity, beautyAndPersonalCare, businessServices, ECommerce, Education, financialServices, foodAndBeverage, Games, Health, homeImprovement, houseHoldProducts, lifeServices, newsAndEntertainment, pets, sportsAndOutdoor, techElectronics, travel, vehicleTransportation, categories }