/**
 * SDUI Fallback Config — used when the backend is unreachable.
 * Mirrors the shape of GET /api/sdui/config so the UI always renders.
 */
export function getSDUIFallbackConfig() {
    return {
        schema_version: '1.0.0',
        config_version: 0,
        searchbar: [
            {
                _id: 'search_input',
                config_type: 'searchbar',
                title: 'Search',
                rank: 1,
                collapsed_by_default: false,
                visible: true,
                icon: { type: 'none', value: '' },
                display_mode: 'input',
                filters: [
                    {
                        _id: 'search_autocomplete',
                        group_id: 'search_input',
                        label: 'Search',
                        type: 'autocomplete',
                        rank: 1,
                        query_param: 'q',
                        visible: true,
                        placeholder: 'Search keyword, advertiser, or domain...',
                        debounce_ms: 300,
                        min_length: 3,
                        platform_applicability: 'all',
                        suggestion_sources: [
                            {
                                _id: 'word_suggest',
                                rank: 1,
                                label: 'Suggestions',
                                method: 'GET',
                                endpoint: '/suggest',
                                env_key: 'VITE_SUGGEST_API_BASE_URL',
                                query_params: { query: 'lastWord', limit: 5, list: 'google', fuzzy: false },
                                response_key: 'suggestions',
                                display_field: 'word',
                                min_chars_to_trigger: 3,
                                on_select_action: 'replacePartialWord',
                            },
                            {
                                _id: 'category_suggest',
                                rank: 2,
                                label: 'Categories',
                                method: 'POST',
                                endpoint: '/search',
                                env_key: 'VITE_CAT_SEARCH_API_BASE_URL',
                                request_body: { query: '', top_k: 5 },
                                response_key: 'matches',
                                display_field: 'sub_category',
                                min_chars_to_trigger: 3,
                                on_select_action: 'setSelCategories',
                            },
                        ],
                        options: [],
                    },
                ],
            },
            {
                _id: 'search_type',
                config_type: 'searchbar',
                title: 'Search Type',
                rank: 2,
                collapsed_by_default: false,
                visible: true,
                icon: { type: 'none', value: '' },
                display_mode: 'dropdown',
                filters: [
                    {
                        _id: 'search_scope',
                        group_id: 'search_type',
                        label: 'Search In',
                        type: 'radio',
                        rank: 1,
                        query_param: 'search_type',
                        visible: true,
                        platform_applicability: 'all',
                        options: [
                            { _id: 'st_keyword', label: 'Keyword', value: 'keyword', rank: 1, selected_by_default: true },
                            { _id: 'st_advertiser', label: 'Advertiser', value: 'advertiser', rank: 2, selected_by_default: false },
                            { _id: 'st_domain', label: 'Domain', value: 'domain', rank: 3, selected_by_default: false },
                        ],
                    },
                ],
            },
        ],
        navbar: [
            {
                _id: 'platforms',
                config_type: 'navbar',
                title: 'Platforms',
                rank: 1,
                collapsed_by_default: false,
                visible: true,
                icon: { type: 'none', value: '' },
                display_mode: 'icon_pill',
                filters: [
                    {
                        _id: 'platform_selector',
                        group_id: 'platforms',
                        label: 'Platform',
                        type: 'icon_toggle',
                        rank: 1,
                        query_param: 'platform',
                        multi_select: true,
                        visible: true,
                        platform_applicability: 'all',
                        platform_filter_matrix: {
                            facebook: ['category', 'engagement', 'cta', 'language', 'gender', 'age', 'country'],
                            instagram: ['category', 'engagement', 'cta', 'language', 'country'],
                            youtube: ['category', 'engagement', 'cta', 'language', 'country'],
                        },
                        options: [
                            { _id: 'p_fb', label: 'FB', value: 'facebook', rank: 1, selected_by_default: true },
                            { _id: 'p_ig', label: 'IG', value: 'instagram', rank: 2, selected_by_default: true },
                            { _id: 'p_yt', label: 'YT', value: 'youtube', rank: 3, selected_by_default: false },
                            { _id: 'p_google', label: 'GGL', value: 'google', rank: 4, selected_by_default: false },
                            { _id: 'p_linkedin', label: 'IN', value: 'linkedin', rank: 5, selected_by_default: false },
                        ],
                    },
                ],
            },
            {
                _id: 'sorting',
                config_type: 'navbar',
                title: 'Sort',
                rank: 3,
                collapsed_by_default: false,
                visible: true,
                icon: { type: 'none', value: '' },
                display_mode: 'dropdown',
                filters: [
                    {
                        _id: 'sort_by',
                        group_id: 'sorting',
                        label: 'Sort By',
                        type: 'radio',
                        rank: 1,
                        query_param: 'sort',
                        visible: true,
                        platform_applicability: 'all',
                        options: [
                            { _id: 's_newest', label: 'Newest', value: 'newest', rank: 1, selected_by_default: true },
                            { _id: 's_popular', label: 'Popular', value: 'popular', rank: 2, selected_by_default: false },
                            { _id: 's_running', label: 'Running Longest', value: 'running_longest', rank: 3, selected_by_default: false },
                        ],
                    },
                ],
            },
        ],
        sidebar: [
            {
                _id: 'category',
                config_type: 'sidebar',
                title: 'Category',
                rank: 1,
                collapsed_by_default: false,
                visible: true,
                icon: { type: 'none', value: '' },
                display_mode: 'accordion',
                filters: [
                    {
                        _id: 'categories',
                        group_id: 'category',
                        label: 'Category',
                        type: 'nested_select',
                        rank: 1,
                        query_param: 'category',
                        visible: true,
                        platform_applicability: 'all',
                        options: [
                            { _id: 'cat_ecom', label: 'E-Commerce', value: 'ecommerce', rank: 1, children: [] },
                            { _id: 'cat_finance', label: 'Finance', value: 'finance', rank: 2, children: [] },
                            { _id: 'cat_health', label: 'Health', value: 'health', rank: 3, children: [] },
                            { _id: 'cat_edu', label: 'Education', value: 'education', rank: 4, children: [] },
                            { _id: 'cat_tech', label: 'Technology', value: 'technology', rank: 5, children: [] },
                        ],
                    },
                ],
            },
            {
                _id: 'cta',
                config_type: 'sidebar',
                title: 'Call to Action',
                rank: 3,
                collapsed_by_default: false,
                visible: true,
                icon: { type: 'none', value: '' },
                display_mode: 'accordion',
                filters: [
                    {
                        _id: 'cta_filter',
                        group_id: 'cta',
                        label: 'CTA',
                        type: 'chip_multi_select',
                        rank: 1,
                        query_param: 'cta',
                        visible: true,
                        platform_applicability: 'all',
                        options: [
                            { _id: 'cta_shop', label: 'Shop Now', value: 'shop_now', rank: 1 },
                            { _id: 'cta_learn', label: 'Learn More', value: 'learn_more', rank: 2 },
                            { _id: 'cta_signup', label: 'Sign Up', value: 'sign_up', rank: 3 },
                        ],
                    },
                ],
            },
            {
                _id: 'country',
                config_type: 'sidebar',
                title: 'Country',
                rank: 9,
                collapsed_by_default: true,
                visible: true,
                icon: { type: 'none', value: '' },
                display_mode: 'accordion',
                filters: [
                    {
                        _id: 'country_filter',
                        group_id: 'country',
                        label: 'Country',
                        type: 'combobox',
                        rank: 1,
                        query_param: 'country',
                        visible: true,
                        platform_applicability: 'all',
                        options: [
                            { _id: 'c_us', label: 'United States', value: 'US', rank: 1 },
                            { _id: 'c_uk', label: 'United Kingdom', value: 'UK', rank: 2 },
                            { _id: 'c_ca', label: 'Canada', value: 'CA', rank: 3 },
                            { _id: 'c_au', label: 'Australia', value: 'AU', rank: 4 },
                            { _id: 'c_in', label: 'India', value: 'IN', rank: 5 },
                        ],
                    },
                ],
            },
        ],
    };
}

export default { getSDUIFallbackConfig };
