import { defineConfig } from "vitest/config";
import react from "@vitejs/plugin-react";

export default defineConfig({
  plugins: [react()],
  test: {
    globals: true,
    environment: "jsdom",
    include: ["tests/**/*.test.{js,jsx,mjs}"],
    setupFiles: ["tests/setup.js"],
    coverage: {
      provider: "v8",
      reporter: ["text", "html", "json-summary"],
      include: [
        "src/constants/sduiVersions.js",
        "src/services/sduiVersionCheck.js",
        "src/lib/utils.js",
        "src/components/ui/animated-theme-toggler.jsx",
        "src/store/uiSlice.js",
        "src/store/store.js",
        "src/services/sduiNormalizer.js",
        "src/constants/index.js",
        "src/config/defaultConfig.js",
        "src/services/sduiService.js",
        "src/hooks/useDebounce.js",
        "src/hooks/useBrowserHistoryState.js",
        "src/i18n.js",
        "src/hooks/useFilters.js",
        "src/hooks/useSDUIPolling.js",
        "src/hooks/useNotifications.js",
        "src/hooks/useAuth.jsx",
        "src/firebase/firebase.js",
        "src/hooks/usePushNotifications.js",
        "src/hooks/useTheme.jsx",
        "src/hooks/useGuest.jsx",
        "src/hooks/useAdInsights.js",
        "src/hooks/useSDUI.js",
        "src/services/api.js",
        "src/services/adPdf.js",
        "src/main.jsx",
        "src/components/filters/FilterChip.jsx",
        "src/components/filters/RangeFilter.jsx",
        "src/components/filters/SegmentedControl.jsx",
        "src/components/filters/PlatformToggle.jsx",
        "src/components/filters/FilterRadioList.jsx",
        "src/components/filters/ComboboxFilter.jsx",
        "src/components/filters/ChipMultiSelect.jsx",
        "src/components/filters/ToggleSwitchFilter.jsx",
        "src/components/filters/DateRangeFilter.jsx",
        "src/components/filters/FilterCheckboxList.jsx",
        "src/components/filters/DatePresetFilter.jsx",
        "src/components/filters/CategorySearchFilter.jsx",
        "src/components/filters/ChipCluster.jsx",
        "src/components/filters/NestedMultiselectFilter.jsx",
        "src/components/filters/AutocompleteFilter.jsx",
        "src/components/filters/SliderFilter.jsx",
        "src/components/shared/SidebarDivider.jsx",
        "src/components/shared/PlatformTab.jsx",
        "src/components/shared/SectionLabel.jsx",
        "src/components/shared/NavItem.jsx",
        "src/components/shared/StatPill.jsx",
        "src/components/sdui/SDUIIcon.jsx",
        "src/components/modals/AIAnalysisModal.jsx",
        "src/components/modals/PricingModal.jsx",
        "src/components/modals/SubscriptionModal.jsx",
        "src/components/modals/CampaignModal.jsx",
        "src/components/shared/ChatbotWidget.jsx",
        "src/components/sdui/DocumentSection.jsx",
        "src/components/modals/analytics/AudienceSection.jsx",
        "src/components/modals/analytics/AnalyticsHeader.jsx",
        "src/components/modals/analytics/AdDetails.jsx",
        "src/components/modals/analytics/LanderDetails.jsx",
        "src/components/sdui/componentMap.js",
        "src/components/sdui/SchemaRenderer.jsx",
        "src/components/layout/NotificationPermissionPrompt.jsx",
        "src/components/layout/NotificationPopup.jsx",
        "src/components/modals/analytics/DateRangePicker.jsx",
        "src/components/modals/analytics/TikTokTimeAnalysis.jsx",
        "src/components/modals/analytics/BasicInfo.jsx",
        "src/components/modals/analytics/Demographics.jsx",
        "src/components/layout/Sidebar.jsx",
        "src/components/ads/Masonry.jsx",
        "src/components/ads/AdFilterBar.jsx",
      ],
      exclude: ["tests/**", "**/node_modules/**", "coverage/**"],
    },
  },
});

