'use strict';

const LANG_ISO_TO_ES = {
  en: 'english',        es: 'spanish',        de: 'german',         fr: 'french',
  ar: 'arabic',         nl: 'dutch',          it: 'italian',        pt: 'portuguese',
  ja: 'japanese',       id: 'indonesian',     ro: 'romanian',       no: 'norwegian',
  ko: 'korean',         sv: 'swedish',        vi: 'vietnamese',     ru: 'russian',
  th: 'thai',           hu: 'hungarian',      el: 'greek',          ms: 'malay',
  pl: 'polish',         tr: 'turkish',        da: 'danish',         cs: 'czech',
  fi: 'finnish',        uk: 'ukrainian',      ca: 'catalan',        sl: 'slovenian',
  fil: 'filipino',      he: 'hebrew',         kk: 'kazakh',         fa: 'persian',
  cy: 'welsh',          hi: 'hindi',          zh: 'chinese',        'zh-cn': 'chinese simplified',
  'zh-tw': 'chinese traditional',             om: 'oromo',          ab: 'abkhazian',
  aa: 'afar',           af: 'afrikaans',      sq: 'albanian',       am: 'amharic',
  an: 'aragonese',      hy: 'armenian',       as: 'assamese',       av: 'avaric',
  ay: 'aymara',         az: 'azerbaijani',    ba: 'bashkir',        eu: 'basque',
  be: 'belarusian',     bn: 'bengali',        dz: 'bhutani',        bh: 'bihari',
  bi: 'bislama',        bs: 'bosnian',        br: 'breton',         bg: 'bulgarian',
  my: 'burmese',        km: 'cambodian',      ce: 'chechen',        cv: 'chuvash',
  kw: 'cornish',        co: 'corsican',       hr: 'croatian',       eo: 'esperanto',
  et: 'estonian',       fo: 'faeroese',       fj: 'fijian',         fy: 'frisian',
  gl: 'galician',       ka: 'georgian',       kl: 'greenlandic',    gn: 'guarani',
  gu: 'gujarati',       ht: 'haitian creole', ha: 'hausa',          is: 'icelandic',
  io: 'ido',            ia: 'interlingua',    ie: 'interlingue',    ik: 'inupiak',
  ga: 'irish',          jv: 'javanese',       kn: 'kannada',        ks: 'kashmiri',
  rw: 'kinyarwanda',    ky: 'kirghiz',        rn: 'kirundi',        ku: 'kurdish',
  lo: 'laothian',       la: 'latin',          lv: 'latvian',        li: 'limburgan',
  ln: 'lingala',        lt: 'lithuanian',     lb: 'luxembourgish',  mk: 'macedonian',
  mg: 'malagasy',       ml: 'malayalam',      dv: 'maldivian',      mt: 'maltese',
  gv: 'manx',           mi: 'maori',          mr: 'marathi',        mo: 'moldavian',
  mn: 'mongolian',      na: 'nauru',          ne: 'nepali',         nn: 'norwegian nynorsk',
  oc: 'occitan',        or: 'odia',           os: 'ossetian',       ps: 'pashto',
  pa: 'punjabi',        qu: 'quechua',        rm: 'rhaeto-romance', sm: 'samoan',
  sg: 'sangro',         sa: 'sanskrit',       sc: 'sardinian',      gd: 'scots gaelic',
  sr: 'serbian',        sh: 'serbo-croatian', st: 'sesotho',        tn: 'setswana',
  sn: 'shona',          sd: 'sindhi',         si: 'singhalese',     ss: 'siswati',
  sk: 'slovak',         so: 'somali',         su: 'sundanese',      sw: 'swahili',
  tl: 'tagalog',        tg: 'tajik',          ta: 'tamil',          tt: 'tatar',
  te: 'telugu',         bo: 'tibetan',        ti: 'tigrinya',       to: 'tonga',
  ts: 'tsonga',         tk: 'turkmen',        tw: 'twi',            ur: 'urdu',
  ug: 'uyghur',         uz: 'uzbek',          vo: 'volapuk',        wa: 'walloon',
  wo: 'wolof',          xh: 'xhosa',          yi: 'yiddish',        yo: 'yoruba',
  zu: 'zulu',
};

module.exports = { LANG_ISO_TO_ES };
